### ISSUE TITLE
[BUG]: Remote list query cannot find the latest version

### ISSUE THREAD

**Issue by heqiaomu** [jaronnie/gvm#1]
The current version is go1.21.3, but the latest version on the official website is go1.21.5. During the process of using GVM list - r, I am unable to find the latest version on the official website.
<img width="313" alt="image" src="https://github.com/jaronnie/gvm/assets/117645192/e74ee35b-7053-40c4-8552-673d65cf8a84">
But I can perform the GVM install go1.21.5 operation
<img width="710" alt="image" src="https://github.com/jaronnie/gvm/assets/117645192/8cc3ed9b-e265-431f-868d-105404a33f25">

**Comment by jaronnie** [comment]
提供一下 gvm version 的值, 可能是因为有 cache.

**Comment by jaronnie** [comment]
在最新版本中, gvm list -r --cache 从缓存中获取，gvm list -r 每次都会拉最新的

**Comment by jaronnie** [comment]
![Uploading iShot_2023-12-27_10.20.55.png…]()

**Comment by jaronnie** [comment]
![image-20231227102154038](https://oss.jaronnie.com/image-20231227102154038.png)
